apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: classifier-api
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: classifier-api
  metrics:
    - type: Pods
      pods:
        metric:
          name: checkout_transactions_per_second
        target:
          type: AverageValue
          averageValue: "100"
