apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: default
data:
  config.yaml: |-
    rules:
      default: false
      custom:
        - seriesQuery: 'predict_latency_count'
          resources:
            overrides:
              namespace: { resource: "namespace" }
              pod: { resource: "pod" }
          name:
            matches: "^(.*)$"
            as: "${1}"
          metricsQuery: 'sum(rate(predict_latency_count[2m])) by (<<.GroupBy>>)'
